const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const code=html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1];
const context=vm.createContext({TextEncoder});
vm.runInContext(code+';this.engine=Engine;',context);
const E=context.engine;
const cards=[{id:'a',ad:'Maximum',program:'maximum',aktif:true},{id:'b',ad:'Bankkart',program:'bankkart',aktif:true},{id:'c',ad:'Bonus',program:'bonus',aktif:true}];
const q={amount:32000,date:'2026-09-18',category:'seyahat',channel:'her'};
const campaign={id:'flight',program:'bankkart',baslangic:'2026-09-01',bitis:'2026-09-30',baslik:'Uçak bileti',kategori:['seyahat'],minHarcama:4000,kademeler:[{minHarcama:4000,sabitKazanc:350},{minHarcama:10000,sabitKazanc:800},{minHarcama:25000,sabitKazanc:1500},{minHarcama:50000,sabitKazanc:3000},{minHarcama:100000,sabitKazanc:6000}],ustLimit:6000,puanTipi:'serbest',hesaplanabilir:true,tahmini:false};
const hotel={...campaign,id:'hotel',program:'maximum',baslik:'ETS %5 indirim',marka:'ETS',kademeler:null,minHarcama:0,oran:.05,puanTipi:'nakit',ustLimit:null};

test('32000 TL compares actual campaign rewards across brands without statement dates',()=>{const r=E.rank(cards,[campaign,hotel],q);assert.equal(r[0].card.id,'a');assert.equal(r[0].total,1600);assert.equal(r[1].total,1500);assert.equal(r[0].campaign.marka,'ETS');});
test('Old interest, statement day and coefficients do not affect ranking',()=>{const old=cards.map((c,i)=>({...c,kesimGunu:i+1}));assert.equal(E.rank(old,[campaign],{...q,interest:.3},{gap:30,weights:{serbest:.4}})[0].total,1500);});
test('Points retain their stated TL value, including brand-locked points',()=>{for(const puanTipi of ['serbest','markaKilitli','nakit'])assert.equal(E.value({...campaign,puanTipi},q).total,1500);});
test('Tier boundaries select earned reward, never headline maximum',()=>{for(const [amount,result] of [[3999,0],[4000,350],[9999,350],[10000,800],[24999,800],[25000,1500],[49999,1500],[50000,3000],[100000,6000]])assert.equal(E.value(campaign,{...q,amount}).total,result);});
test('Bounded tiers and gaps do not fall back to another reward',()=>{const c={...campaign,sabitKazanc:9000,kademeler:[{minHarcama:4000,maxHarcama:9999,sabitKazanc:350},{minHarcama:20000,maxHarcama:30000,sabitKazanc:800}]};assert.equal(E.value(c,q).total,0);assert.equal(E.value(c,{...q,amount:15000}).total,0);});
test('Percentage and fixed rewards honor caps and minimums',()=>{assert.equal(E.value({...hotel,ustLimit:1000},q).total,1000);assert.equal(E.value({...hotel,oran:null,sabitKazanc:2000,ustLimit:1500},q).total,1500);assert.equal(E.value({...hotel,minHarcama:35000},q).total,0);});
test('Uncertain amount and missing minimum never create a reward',()=>{for(const c of [{...campaign,tahmini:true},{...campaign,hesaplanabilir:false},{...campaign,minHarcama:null}])assert.equal(E.value(c,q).total,0);});
test('No monetary campaign produces no selected winner campaign',()=>{const r=E.rank(cards,[],q);assert(r.every(x=>x.total===0&&x.campaign===null));});
test('Installments alone have no monetary reward',()=>{const c={...hotel,oran:null,taksitAy:12,pesinFiyatina:true};assert.equal(E.value(c,{...q,interest:.03,installments:true}).total,0);assert.equal(E.rank(cards,[c],q)[0].campaign,null);});
test('Distinct campaigns are never added together',()=>{assert.equal(E.rank(cards,[hotel,{...hotel,id:'second',oran:.06}],q)[0].total,1920);});
test('All brands considered; channel and private card scope still apply',()=>{const c={...hotel,kanal:'online',kartId:'a'};assert(E.matches(c,cards[0],q));assert(!E.matches(c,cards[0],{...q,channel:'fiziksel'}));assert(E.matches(c,cards[0],{...q,channel:'online'}));assert(!E.matches(c,{...cards[0],id:'other'},q));});
test('Expired, future and undated campaigns are excluded',()=>{assert(E.active(campaign,'2026-09-30'));assert(!E.active(campaign,'2026-10-01'));assert(!E.active(campaign,'2026-08-31'));assert(!E.active({...campaign,baslangic:null},q.date));assert.equal(E.rank(cards,[{...campaign,bitis:'2026-09-17'}],q)[0].campaign,null);});
test('Disabled cards do not participate',()=>{assert.equal(E.rank([{...cards[0],aktif:false},cards[1]],[campaign,hotel],q)[0].card.id,'b');});
test('Invalid date and amount rejected',()=>{assert.throws(()=>E.date('2026-02-30'));assert.throws(()=>E.rank(cards,[],{...q,amount:0}));assert.throws(()=>E.rank(cards,[],{...q,amount:NaN}));assert.throws(()=>E.rank(cards,[],{...q,amount:1e9}));});
test('Calendar lists campaign expiration, monetary benefit, brand and conditions',()=>{const ics=E.calendar(cards,[{...hotel,kosul:'Yalnız seçili oteller.',katilimGerekli:true},campaign],q),text=ics.replace(/\r\n /g,'');assert.match(text,/DTSTART;VALUE=DATE:20260930\r\nDTEND;VALUE=DATE:20261001/);assert.match(text,/TRIGGER;VALUE=DATE-TIME:20260929T170000Z/);assert.match(text,/1600 TL/);assert.match(text,/Geçerli marka: ETS/);assert.match(text,/Yalnız seçili oteller/);assert.doesNotMatch(text,/vade|faiz|getiri|kesim/i);assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,2);for(const line of ics.split('\r\n'))assert(Buffer.byteLength(line,'utf8')<=75);});
test('Same campaign on two personal cards creates one calendar event',()=>{assert.equal((E.calendar([cards[0],{...cards[0],id:'a2'}],[hotel],q).match(/BEGIN:VEVENT/g)||[]).length,1);});
test('Calendar excludes unsupported and ineligible offers',()=>{const ics=E.calendar(cards,[{...hotel,tahmini:true},{...campaign,minHarcama:50000}],q);assert.doesNotMatch(ics,/BEGIN:VEVENT/);});
test('ICS escapes newline, semicolon, comma and backslash',()=>assert.equal(E.escapeICS('a,b;c\nd\\e'),'a\\,b\\;c\\nd\\\\e'));
test('All application scripts parse after removed form fields',()=>{for(const script of html.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);});
test('Existing personal cards and participation survive removal of old assumptions',()=>{const app=html.match(/<script>\s*'use strict';([\s\S]*?)<\/script>/)[1];const prefix=app.slice(0,app.indexOf('function campaigns()'));const ctx=vm.createContext({structuredClone});vm.runInContext(prefix+';this.validate=validateState;',ctx);const old={cards:Array.from({length:4},(_,i)=>({id:'k'+i,ad:'Kart '+i,sahip:'Test',program:'maximum',aktif:true,renk:'#ae176e',kesimGunu:20})),settings:{gap:10,weights:{nakit:1,serbest:.8,markaKilitli:.4}},interest:3,manual:[],joined:{'campaign|period|k0':true}};const migrated=ctx.validate(old);assert.equal(migrated.cards[0].sahip,'Test');assert.equal(migrated.joined['campaign|period|k0'],true);assert(!('settings' in migrated));assert(!('kesimGunu' in migrated.cards[0]));assert.equal(ctx.validate(migrated).cards.length,4);});
