const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const code=html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1];
const context=vm.createContext({TextEncoder});
vm.runInContext(code+';this.engine=Engine;',context);
const E=context.engine;
const settings={gap:10,weights:{nakit:1,serbest:.8,markaKilitli:.4}};
const cards=[{id:'a',ad:'Maximum',program:'maximum',aktif:true,kesimGunu:20},{id:'b',ad:'Bankkart',program:'bankkart',aktif:true,kesimGunu:5}];
const q={amount:5000,date:'2026-09-16',category:'market',brand:'',channel:'fiziksel',interest:.03,installments:true};
const campaign={id:'one',program:'bankkart',baslangic:'2026-09-01',bitis:'2026-09-30',baslik:'Market',kategori:['market'],minHarcama:5000,sabitKazanc:250,ustLimit:1000,puanTipi:'serbest',hesaplanabilir:true,tahmini:false};

test('Exact cut date uses this statement; next day uses next month',()=>{assert.equal(E.maturity('2026-09-20',20).days,10);assert.equal(E.maturity('2026-09-21',20).days,39);});
test('Real month lengths, leap years and year change',()=>{assert.equal(E.maturity('2026-02-27',31).closing,'2026-02-28');assert.equal(E.maturity('2028-02-28',31).days,11);assert.equal(E.maturity('2026-12-31',5).due,'2027-01-15');});
test('Invalid calendar date and invalid cut rejected',()=>{assert.throws(()=>E.date('2026-02-30'));assert.throws(()=>E.maturity('2026-09-16',0));});
test('Maturity only ranking and example 345 TL',()=>{const r=E.rank(cards,[campaign],q,settings);assert.equal(r[0].card.id,'b');assert.equal(r[0].term.days,29);assert.equal(r[0].maturityValue,145);assert.equal(r[0].reward,200);assert.equal(r[0].total,345);});
test('Uncertain cap never becomes a reward',()=>{const c={...campaign,tahmini:true,sabitKazanc:1250};assert.equal(E.value(c,q,settings.weights).total,0);const no={...campaign,hesaplanabilir:false};assert.equal(E.value(no,q,settings.weights).total,0);});
test('Minimum and date boundaries are inclusive',()=>{assert.equal(E.matches(campaign,cards[1],q),true);assert.equal(E.matches(campaign,cards[1],{...q,amount:4999}),false);assert.equal(E.active(campaign,'2026-09-30'),true);assert.equal(E.active(campaign,'2026-10-01'),false);assert.equal(E.active({...campaign,baslangic:null},q.date),false);});
test('Brand exact match, Turkish normalization, channel and private card scope',()=>{const c={...campaign,marka:'CarrefourSA',kanal:'fiziksel',kartId:'b'};assert(E.matches(c,cards[1],{...q,brand:'carrefour sa'}));assert(!E.matches(c,cards[1],{...q,brand:''}));assert(!E.matches(c,cards[1],{...q,brand:'CarrefourSA',channel:'online'}));assert(!E.matches(c,{...cards[1],id:'other'},{...q,brand:'CarrefourSA'}));assert.equal(E.norm('IŞIK'),E.norm('ışık'));});
test('Rate cap and reward coefficient',()=>{const c={...campaign,oran:.1,sabitKazanc:null,ustLimit:300};assert.equal(E.value(c,q,settings.weights).reward,240);assert.equal(E.value({...c,puanTipi:'markaKilitli'},q,settings.weights).reward,120);});
test('Tiered first-purchase reward',()=>{const c={...campaign,kademeler:[{minHarcama:10000,sabitKazanc:500},{minHarcama:20000,sabitKazanc:1000}]};assert.equal(E.value(c,{...q,amount:10000},settings.weights).reward,400);assert.equal(E.value(c,{...q,amount:20000},settings.weights).reward,800);});
test('30000 TL over six months at 3% is 2250 TL',()=>{const c={...campaign,sabitKazanc:null,taksitAy:6,pesinFiyatina:true};assert.equal(E.value(c,{...q,amount:30000},settings.weights).installment,2250);assert.equal(E.value(c,{...q,installments:false},settings.weights).installment,0);assert.equal(E.value({...c,pesinFiyatina:false},q,settings.weights).installment,0);});
test('Different campaigns are never stacked',()=>{const r=E.rank(cards,[campaign,{...campaign,id:'second',sabitKazanc:500}],q,settings);assert.equal(r[0].reward,400);assert.equal(r[0].campaign.id,'second');});
test('Zero amount and excessive return rejected, zero return allowed',()=>{assert.throws(()=>E.rank(cards,[],{...q,amount:0},settings));assert.throws(()=>E.rank(cards,[],{...q,interest:1},settings));assert.equal(E.rank(cards,[],{...q,interest:0},settings)[0].total,0);});
test('Only active cards participate',()=>assert.equal(E.rank([{...cards[0],aktif:false},cards[1]],[],q,settings).length,1));
test('Cycle and half-month periods cross year correctly',()=>{const cycle=E.periods('2026-12-18',2,'cycle');assert.equal(cycle[0].start,'2026-12-21');assert.equal(cycle[0].end,'2027-01-05');const half=E.periods('2026-02-01',1,'half');assert.equal(half[1].end,'2026-02-28');});
test('ICS has all-day event, previous 20:00 Turkey alarm, all categories',()=>{const cats={market:'Market',akaryakit:'Akaryakıt',yemek:'Yemek',giyim:'Giyim',elektronik:'Elektronik',seyahat:'Seyahat',online:'Online'};const ics=E.calendar(cards,[campaign],q,settings,cats,'2026-09-17',3,'cycle');const unfolded=ics.replace(/\r\n /g,'');assert.match(unfolded,/DTSTART;VALUE=DATE:20260921\r\nDTEND;VALUE=DATE:20260922/);assert.match(unfolded,/TRIGGER;VALUE=DATE-TIME:20260920T170000Z/);assert.match(unfolded,/Akaryakıt:/);assert.match(unfolded,/otomatik güncellenmez/);for(const line of ics.split('\r\n'))assert(Buffer.byteLength(line,'utf8')<=75);assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,6);});
test('ICS escapes newline, semicolon, comma and backslash',()=>assert.equal(E.escapeICS('a,b;c\nd\\e'),'a\\,b\\;c\\nd\\\\e'));
